trigger:
  branches:
    include: ["master", "azure-pipelines"]
  tags:
    include: ["*"]

jobs:
  - job: "Clippy"
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    strategy:
      matrix:
        windows-stable:
          imageName: "windows-latest"
          rustup_toolchain: stable
        linux-stable:
          imageName: "ubuntu-latest"
          rustup_toolchain: stable
        macos-stable:
          imageName: "macOS-latest"
          rustup_toolchain: stable

    pool:
      vmImage: $(imageName)

    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Linux Darwin Install Rust
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
      - script: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN% --default-host x86_64-pc-windows-msvc
          echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
        displayName: Windows Install Rust
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
      - script: rustup component add clippy
        displayName: Install Clippy
      - script: cargo clippy --all
        displayName: Run Clippy

  - job: "Test"
    condition: not(startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    strategy:
      matrix:
        windows-stable:
          imageName: "windows-latest"
          rustup_toolchain: stable
        linux-stable:
          imageName: "ubuntu-latest"
          rustup_toolchain: stable
        macos-stable:
          imageName: "macOS-latest"
          rustup_toolchain: stable

    pool:
      vmImage: $(imageName)

    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Linux Darwin Install Rust
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
      - script: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN% --default-host x86_64-pc-windows-msvc
          echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
        displayName: Windows Install Rust
        condition: eq( variables['Agent.OS'], 'Windows_NT' )
      - script: cargo build --all
        displayName: Cargo Build
      - script: cargo test --all
        displayName: Cargo Test

  - job: "Release"
    timeoutInMinutes: 0
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    strategy:
      matrix:
        windows-stable:
          imageName: "windows-latest"
          rustup_toolchain: stable
          target: "x86_64-pc-windows-msvc"
          docker: false
        linux-stable:
          imageName: "ubuntu-latest"
          rustup_toolchain: stable
          target: "x86_64-unknown-linux-gnu"
          docker: false
        macos-stable:
          imageName: "macOS-latest"
          rustup_toolchain: stable
          target: "x86_64-apple-darwin"
          docker: false
        armv7-stable:
          imageName: "ubuntu-latest"
          rustup_toolchain: stable
          target: "armv7-unknown-linux-gnueabihf"
          docker: true
        aarch64-stable:
          imageName: "ubuntu-latest"
          rustup_toolchain: stable
          target: "aarch64-unknown-linux-gnu"
          docker: true

    pool:
      vmImage: $(imageName)

    steps:
      - bash: |
          DATE="$(date +%Y-%m-%d)"
          echo "##vso[task.setvariable variable=build.date]$DATE"
        displayName: Create Date Variable
      - bash: |
          MY_TAG="$(Build.SourceBranch)"
          MY_TAG=${MY_TAG#refs/tags/}
          echo $MY_TAG
          echo "##vso[task.setvariable variable=build.my_tag]$MY_TAG"
        displayName: Create Tag Variable
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: Linux Darwin Install Rust
        condition: and( ne( variables['Agent.OS'], 'Windows_NT' ), eq( variables['docker'], 'false' ))
      - script: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN% --default-host x86_64-pc-windows-msvc
          echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
        displayName: Windows Install Rust
        condition: and( eq( variables['Agent.OS'], 'Windows_NT' ), eq( variables['docker'], 'false' ))
      - script: cargo build --release --all
        displayName: Cargo Build
        condition: eq( variables['docker'], 'false' )
      - script: cargo test --release --all
        displayName: Cargo Test
        condition: eq( variables['docker'], 'false' )

      - script: |
          docker build -t tbd:$TARGET ./ci/$TARGET/
        displayName: Cross Setup Docker
        condition: eq( variables['docker'], 'true' )
      - script: |
          docker run -v "$(pwd):/source" tbd:$TARGET cargo build --release --manifest-path /source/Cargo.toml --target $TARGET
        displayName: Cross Build
        condition: eq( variables['docker'], 'true' )
      - task: CopyFiles@2
        displayName: Copy Binary
        inputs:
          sourceFolder: "$(Build.SourcesDirectory)"
          contents: |
            target/**/release/?(tbd|tbd.exe)
          targetFolder: "$(Build.BinariesDirectory)/tbd"
          flattenFolders: true
      - task: CopyFiles@2
        displayName: Copy Assets
        inputs:
          sourceFolder: "$(Build.SourcesDirectory)"
          contents: |
            README.md
          targetFolder: "$(Build.BinariesDirectory)/tbd"

      - task: ArchiveFiles@2
        displayName: Linux Darwin Archive
        inputs:
          rootFolderOrFile: "$(Build.BinariesDirectory)/tbd"
          archiveType: "tar"
          tarCompression: "gz"
          archiveFile: "$(Build.ArtifactStagingDirectory)/tbd-$(build.my_tag)-$(TARGET).tar.gz"
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
      - task: ArchiveFiles@2
        displayName: Windows Archive
        inputs:
          rootFolderOrFile: "$(Build.BinariesDirectory)/tbd"
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/tbd-$(build.my_tag)-$(TARGET).zip"
        condition: eq( variables['Agent.OS'], 'Windows_NT' )

      - task: GithubRelease@0
        displayName: Publish Assets to Github Release
        condition: succeeded()
        inputs:
          gitHubConnection: "tarkah"
          repositoryName: "tarkah/tbd"
          action: "edit"
          target: "$(build.sourceVersion)"
          tagSource: "manual"
          tag: "$(build.my_tag)"
          assets: "$(Build.ArtifactStagingDirectory)/*"
          title: "$(build.my_tag) - $(build.date)"
          assetUploadMode: "replace"
          addChangeLog: false