[package]
name = "tickrs"
version = "0.1.0"
authors = ["tarkah <admin@tarkah.dev>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/tarkah/tickrs"
readme = "README.md"
description = "Realtime ticker data in your terminal ðŸ“ˆ"
keywords = ["tui","terminal","stocks"]
categories = ["command-line-utilities"]

[workspace]
members = [
    ".",
    "api",
]

[dependencies]
api = { path = "api/", version = "0.1.0" }

anyhow = "1.0"
crossbeam-channel = "0.4"
chrono = "0.4"
chrono-tz = "0.5"
structopt = "0.3"

async-std = "1.5"
futures = "0.3"

better-panic = "0.2"
crossterm = "0.17"
ctrlc = { version = "3.1", features = ["termination"] }
tui = { version = "0.9", default-features = false, features = ["crossterm"] }